from __future__ import annotations

from datetime import datetime, timedelta

from fastapi import APIRouter, Depends
from fastapi.responses import PlainTextResponse
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from ..database import get_session
from ..models import ImageGenerationStat, Run, RunImage, RunImageStatus, RunStatus

router = APIRouter(tags=["metrics"])


def _escape_label_value(value: str) -> str:
    return value.replace("\\", "\\\\").replace("\n", "\\n").replace('"', '\\"')


def _format_metric(name: str, value: int, labels: dict[str, str] | None = None) -> str:
    if labels:
        label_pairs = [f'{key}="{_escape_label_value(val)}"' for key, val in sorted(labels.items())]
        return f"{name}{{{','.join(label_pairs)}}} {value}"
    return f"{name} {value}"


@router.get("/metrics", response_class=PlainTextResponse, include_in_schema=False)
def metrics(session: Session = Depends(get_session)) -> PlainTextResponse:
    status_counts_stmt = (
        select(RunImage.status, func.count())
        .select_from(RunImage)
        .group_by(RunImage.status)
    )
    status_counts = {
        row.status: int(row.count)
        for row in session.execute(status_counts_stmt).all()
    }

    approved_count = status_counts.get(RunImageStatus.APPROVED, 0)
    posted_count = status_counts.get(RunImageStatus.POSTED, 0)

    scheduled_count_stmt = (
        select(func.count())
        .select_from(RunImage)
        .where(
            RunImage.status == RunImageStatus.APPROVED,
            RunImage.scheduled_time.is_not(None),
        )
    )
    scheduled_count = int(session.execute(scheduled_count_stmt).scalar_one() or 0)

    runs_need_review_stmt = (
        select(func.count(func.distinct(RunImage.run_id)))
        .select_from(RunImage)
        .join(Run, Run.id == RunImage.run_id)
        .where(RunImage.status == RunImageStatus.GENERATED, Run.status != RunStatus.POSTED)
    )
    runs_need_review = int(session.execute(runs_need_review_stmt).scalar_one() or 0)

    now = datetime.utcnow()
    
    # Total images generated (counter for rate calculations)
    total_images_stmt = select(func.count()).select_from(ImageGenerationStat)
    total_images_generated = int(session.execute(total_images_stmt).scalar_one() or 0)
    
    # Images generated in different time windows
    last_hour_cutoff = now - timedelta(hours=1)
    last_6h_cutoff = now - timedelta(hours=6)
    last_24h_cutoff = now - timedelta(hours=24)
    
    images_last_hour_stmt = (
        select(func.count())
        .select_from(ImageGenerationStat)
        .where(ImageGenerationStat.generated_at >= last_hour_cutoff)
    )
    images_generated_last_hour = int(session.execute(images_last_hour_stmt).scalar_one() or 0)
    
    images_last_6h_stmt = (
        select(func.count())
        .select_from(ImageGenerationStat)
        .where(ImageGenerationStat.generated_at >= last_6h_cutoff)
    )
    images_generated_last_6h = int(session.execute(images_last_6h_stmt).scalar_one() or 0)
    
    images_last_24h_stmt = (
        select(func.count())
        .select_from(ImageGenerationStat)
        .where(ImageGenerationStat.generated_at >= last_24h_cutoff)
    )
    images_generated_last_24h = int(session.execute(images_last_24h_stmt).scalar_one() or 0)
    
    # Images generated by machine_id
    images_by_machine_stmt = (
        select(ImageGenerationStat.machine_id, func.count())
        .select_from(ImageGenerationStat)
        .where(ImageGenerationStat.generated_at >= last_24h_cutoff)
        .group_by(ImageGenerationStat.machine_id)
    )
    images_by_machine = {
        (row.machine_id or "unknown"): int(row.count)
        for row in session.execute(images_by_machine_stmt).all()
    }

    lines = [
        "# HELP workflow_images_total Count of images by state.",
        "# TYPE workflow_images_total gauge",
        _format_metric("workflow_images_total", approved_count, {"state": "approved"}),
        _format_metric("workflow_images_total", posted_count, {"state": "posted"}),
        _format_metric("workflow_images_total", scheduled_count, {"state": "scheduled"}),
        "# HELP workflow_images_generated_total Total count of images generated (counter).",
        "# TYPE workflow_images_generated_total counter",
        _format_metric("workflow_images_generated_total", total_images_generated),
        "# HELP workflow_images_generated_last_hour Count of images generated in the last hour.",
        "# TYPE workflow_images_generated_last_hour gauge",
        _format_metric("workflow_images_generated_last_hour", images_generated_last_hour),
        "# HELP workflow_images_generated_last_6h Count of images generated in the last 6 hours.",
        "# TYPE workflow_images_generated_last_6h gauge",
        _format_metric("workflow_images_generated_last_6h", images_generated_last_6h),
        "# HELP workflow_images_generated_last_24h Count of images generated in the last 24 hours.",
        "# TYPE workflow_images_generated_last_24h gauge",
        _format_metric("workflow_images_generated_last_24h", images_generated_last_24h),
        "# HELP workflow_images_generated_by_machine Count of images generated by machine in the last 24 hours.",
        "# TYPE workflow_images_generated_by_machine gauge",
    ]
    
    # Add per-machine metrics
    for machine_id, count in images_by_machine.items():
        lines.append(_format_metric("workflow_images_generated_by_machine", count, {"machine_id": machine_id}))
    
    lines.extend([
        "# HELP workflow_runs_need_review Number of runs needing review.",
        "# TYPE workflow_runs_need_review gauge",
        _format_metric("workflow_runs_need_review", runs_need_review),
    ])
    
    payload = "\n".join(lines) + "\n"
    return PlainTextResponse(payload, media_type="text/plain; version=0.0.4")
