-- SQL to insert banned tags
-- Uses INSERT IGNORE to skip duplicates if tags already exist

INSERT IGNORE INTO banned_tags (id, tag, created_at, updated_at) VALUES
(UUID(), 'tagme', NOW(), NOW()),
(UUID(), 'shorter_than_30_seconds', NOW(), NOW()),
(UUID(), 'stable_diffusion', NOW(), NOW()),
(UUID(), 'ai_generated', NOW(), NOW()),
(UUID(), 'pixelated penis', NOW(), NOW()),
(UUID(), 'censored genitalia', NOW(), NOW()),
(UUID(), 'highres', NOW(), NOW()),
(UUID(), 'hi res', NOW(), NOW()),
(UUID(), 'uncensored', NOW(), NOW()),
(UUID(), 'patreon', NOW(), NOW()),
(UUID(), 'english text', NOW(), NOW()),
(UUID(), 'anime', NOW(), NOW()),
(UUID(), 'self upload', NOW(), NOW()),
(UUID(), 'double v', NOW(), NOW()),
(UUID(), 'underwear', NOW(), NOW()),
(UUID(), 'mange style', NOW(), NOW()),
(UUID(), 'manga page', NOW(), NOW()),
(UUID(), 'text', NOW(), NOW()),
(UUID(), 'animated', NOW(), NOW()),
(UUID(), 'manga cover', NOW(), NOW()),
(UUID(), 'username', NOW(), NOW()),
(UUID(), 'patreon username', NOW(), NOW()),
(UUID(), 'speech bubble', NOW(), NOW()),
(UUID(), 'voice acted', NOW(), NOW()),
(UUID(), 'multiple views', NOW(), NOW()),
(UUID(), 'dialogue bubble', NOW(), NOW()),
(UUID(), 'english dialogue', NOW(), NOW()),
(UUID(), 'futadom', NOW(), NOW()),
(UUID(), 'futa with female', NOW(), NOW()),
(UUID(), 'futa', NOW(), NOW()),
(UUID(), 'teen', NOW(), NOW()),
(UUID(), 'dialogue', NOW(), NOW()),
(UUID(), 'japanese text', NOW(), NOW()),
(UUID(), '2koma', NOW(), NOW()),
(UUID(), 'artist name', NOW(), NOW()),
(UUID(), 'shy', NOW(), NOW()),
(UUID(), 'wet', NOW(), NOW()),
(UUID(), 'milk', NOW(), NOW()),
(UUID(), 'milking', NOW(), NOW()),
(UUID(), 'voice', NOW(), NOW()),
(UUID(), 'sound', NOW(), NOW()),
(UUID(), 'sound warning', NOW(), NOW()),
(UUID(), 'reading', NOW(), NOW()),
(UUID(), 'picture frame', NOW(), NOW());



