FROM python:3.11-slim

WORKDIR /app

# Fix for Debian Trixie: libgl1-mesa-glx is replaced with libgl1
RUN apt-get update && apt-get install -y libgl1 libglib2.0-0 && rm -rf /var/lib/apt/lists/*

# Copy the repository files
COPY . .

# Setup environment
RUN cp .env.exp .env
RUN sed -i 's|SERVER_HOST=127.0.0.1|SERVER_HOST=0.0.0.0|' .env

# Install dependencies
RUN pip install pdm
RUN pdm install

EXPOSE 5010

CMD ["pdm", "run", "python", "main.py"]


